export const FETCH_FILING_AUDITS = 'FETCH_FILING_AUDITS';
export const FILING_AUDITS_FETCHED = 'FILING_AUDITS_FETCHED';
export const FILTER_FILING_AUDITS = 'FILTER_FILING_AUDITS';
export const RESET_FILTER_FILING_AUDITS = 'RESET_FILTER_FILING_AUDITS';